<script type="text/javascript" src="http://webapp.easysize.me/web_app_v1.0/js/easysize-2.0.0.js"></script>

<?php if($this->getProductObject()){ ?>
    <script type="text/javascript">
    var easy_size;
    window.onload = function() {   
        var data = <?php echo $this->getObj(); ?>;
        easy_size = new EasySize(data);
        easy_size.start();
    }
    </script>
<?php } ?>

<link href="http://webapp.easysize.me/web_app_v1.0/css/easysize_<?php echo Mage::getStoreConfig('easysize_section/easysize_group/style_field',Mage::app()->getStore());?>.css" rel="stylesheet" />