<style>

.content{
	width: 100%;
	margin: auto;
}
.title{
	text-align: center;
}
#logo{
	width: 140px;
}
.table {
	margin-bottom: 20px;
	max-width: 100%;
	width: 100%;
}
.alert-danger {
	text-align: center;
	background-color: #f2dede;
	border-color: #ebccd1;
	color: #a94442;
}
.alert {
	border: 1px solid transparent;
	border-radius: 4px;
	margin-bottom: 20px;
	padding: 15px;
}
.alert-success {
  color: #3c763d;
  background-color: #dff0d8;
  border-color: #d6e9c6;
}
#form{
	width: 30%;
	float: right;
	padding: 20px;
	margin: 0;
}
</style>
<?php

	
	Mage::app()->getCacheInstance()->flush();

	if(isset($_POST['sizecode'])){
		$sizeCode = $_POST['sizecode'];
		$genderCode = $_POST['gendercode'];
		$placeholder = $_POST['placeholder'];
		$shopid = $_POST['shopid'];
		$design = $_POST['design'];
		$add_to_cart = $_POST['add_to_cart'];

		Mage::getModel('core/config')->saveConfig('easysize_section/easysize_group/size_field', $sizeCode);
		Mage::getModel('core/config')->saveConfig('easysize_section/easysize_group/gender_field', $genderCode);
		Mage::getModel('core/config')->saveConfig('easysize_section/easysize_group/placeholder_field', $placeholder);
		Mage::getModel('core/config')->saveConfig('easysize_section/easysize_group/id_shop_field', $shopid);
		Mage::getModel('core/config')->saveConfig('easysize_section/easysize_group/style_field', $design);
		Mage::getModel('core/config')->saveConfig('easysize_section/easysize_group/add_to_cart_field', $add_to_cart);			
	}else{
		$sizeCode = Mage::getStoreConfig('easysize_section/easysize_group/size_field',Mage::app()->getStore());
		$genderCode = Mage::getStoreConfig('easysize_section/easysize_group/gender_field',Mage::app()->getStore());
		$placeholder = Mage::getStoreConfig('easysize_section/easysize_group/placeholder_field',Mage::app()->getStore());
		$shopid = Mage::getStoreConfig('easysize_section/easysize_group/id_shop_field',Mage::app()->getStore());
		$design = Mage::getStoreConfig('easysize_section/easysize_group/style_field',Mage::app()->getStore());
		$add_to_cart = strlen(Mage::getStoreConfig('easysize_section/easysize_group/add_to_cart_field',Mage::app()->getStore())) > 2 ? Mage::getStoreConfig('easysize_section/easysize_group/add_to_cart_field',Mage::app()->getStore()) : ".add-to-cart-buttons";
	}

	

?>
<div class="content">	

	<div id="form">
		<h2>Configuration</h2>
		<form method="POST" action="" style="max-width: 500px;">
			<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"  />
			<div class="alert alert-danger">
			<h4 class="title">Errors</h4>
			<?php
				$error = false;
				if (!$sizeCode) {
					$error = true;
					echo "<p>- A size code is needed</p></p>";
				} else if (!$this->attributeExistsInTheShop($sizeCode)) {
					echo "<p>- '".$sizeCode."''  is not a valid size code </p>";
					$error = true;
				}

				if (!$genderCode) {
					$error = true;
					echo "<p>- A gender code is needed";
				} else if (!$this->attributeExistsInTheShop($genderCode)){
					$error = true;
					echo "<p>- '".$genderCode."''  is not a valid gender code </p>";
				}

				if (!$placeholder) {
					$error = true;
					echo "<p>- A placeholder is needed</p>";
				}

				if (!$shopid) {
					$error = true;
					echo "<p>- Shop id is needed</p>";
				}

				if (!$error) {
					echo '<style>.alert-danger{display:none;}</style>';
					echo '<style>.alert-success{display:block;}</style>';
				} else {
					echo '<style>.alert-danger{display:block;}</style>';
					echo '<style>.alert-success{display:none;}</style>';
				}
				
			?>
			</div>

			<div class="alert alert-success">
			<h4 class="title">All looks well configured</h4>

			</div>


			<p class="fd">
				<label class="label" for="sizecode"><b>Size Code: </b></label>
				<input style="float: right;" type="text" name="sizecode" id="sizecode" value="<?php echo $sizeCode;?>" /> <br/>
				<i>This code represents the product size in your shop.</i>
			</p>
			
			<p class="fd">
				<label class="label" for="gendercoder"><b>Gender Code: </b></label>
				<input style="float: right;" type="text" name="gendercode" id="gendercode" value="<?php echo $genderCode;?>" /><br/>
				<i>This code represents the product gender in your shop.</i>
			</p>
			
			<p class="fd">
				<label class="label" for="placeholder"><b>Placeholder: </b></label>
				<input style="float: right;" stype="text" name="placeholder" id="placeholder" value="<?php echo $placeholder;?>" /><br/>
				<i>This value controls the position of the EasySize button.</i>
			</p>
			
			<p class="fd">
				<label class="label" for="add_to_cart"><b>Add to cart button: </b></label>
				<input style="float: right;" stype="text" name="add_to_cart" id="add_to_cart" value="<?php echo $add_to_cart;?>" /><br/>
				<i>Your add to cart button selector</i>
			</p>
			
			<p class="fd">
				<label class="label" for="design"><b>Design Name: </b></label>
				<input style="float: right;" type="text" name="design" id="design" value="<?php echo $design;?>" /><br/>
				<i>Change the design of the popup (Ask EasySize team).</i>
			</p>
			
			<p class="fd">
				<label class="label" for="shopid"><b>Shop Id: </b></label>
				<input style="float: right;" type="text" name="shopid" id="shopid" value="<?php echo $shopid;?>" /><br/>
				<i>This value is your shop id provided by EasySize.</i>
			</p>

			<p>
				<button style="width: 100%;" type="submit">Save</button>
			</p>
		</form>

		<h2>Overview</h2>
		<p>Below you will find all configurable product and how they fulfill EasySize parameters</p>
		<i>Note: Each configurable product needs to have a category, a brand (manufacturer attribute), a gender and different(multiple) sizes available.</i>

		<hr/>

		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Category</th>
					<th>Gender</th>
					<th>Brand</th>
					<th>Different(multiple) Sizes?</th>
				</tr>
			</thead>

			<?php 
				$all = $this->getAllProducts($sizeCode, $genderCode);
				for ($i=0; $i<sizeof($all); $i++) {
					if ($all[$i]->valid) {
						echo "<tr style='color: green'>";
					} else {
						echo "<tr style='color: red'>";	
					}

					echo "<td>".$all[$i]->name."</td>";
					echo "<td>".$all[$i]->product_type."</td>";
					echo "<td>".$all[$i]->gender."</td>";
					echo "<td>".$all[$i]->product_brand."</td>";
					echo "<td>".$all[$i]->children."</td>";
					echo "</tr>";
				}
			?>
		</table>

	</div>
	
	<iframe style="float: left; border:none; margin:0;" src="http://www.easysize.me/" height="800px"  width="65%" >EasySize loading...</iframe>
</div>